export const COSTS = {
  legend: 1000,
  attribute: 40,
  dev_up: 250,
  age_reset: 250,
  custom_player_gold: 300,
  custom_player_silver: 200,
  custom_player_bronze: 100,
} as const;

export const LIMITS = {
  attributesPerSeason: 20,
  speedPointsPerSeason: 5,
  devUpsPerSeason: 2,
  ageResetsPerSeason: 2,
  legendsAllTime: 4,
  maxLegendsInInventory: 4,
  maxLegendsPlusCustomPlayers: 7,
} as const;

export const ATTRIBUTES = [
  "Speed",
  "Acceleration",
  "Agility",
  "Strength",
  "Awareness",
  "Stamina",
  "Injury",
  "Toughness",
  "Throw Power",
  "Throw Accuracy Short",
  "Throw Accuracy Mid",
  "Throw Accuracy Deep",
  "Throw on the Run",
  "Play Action",
  "Break Sack",
  "Carrying",
  "Ball Carrier Vision",
  "Stiff Arm",
  "Spin Move",
  "Juke Move",
  "Break Tackle",
  "Catching",
  "Catch in Traffic",
  "Short Route Running",
  "Medium Route Running",
  "Deep Route Running",
  "Spectacular Catch",
  "Release",
  "Run Blocking",
  "Pass Blocking",
  "Impact Blocking",
  "Tackle",
  "Hit Power",
  "Block Shedding",
  "Pursuit",
  "Play Recognition",
  "Man Coverage",
  "Zone Coverage",
  "Press",
  "Kick Power",
  "Kick Accuracy",
  "Kick Return",
] as const;

export const CUSTOM_PLAYER_TIERS = ["gold", "silver", "bronze"] as const;
