export const COSTS = {
  legend: 1000,
  attribute: 40,
  dev_up: 250,
  age_reset: 250,
  custom_player_gold: 300,
  custom_player_silver: 200,
  custom_player_bronze: 100,
} as const;

export const LIMITS = {
  attributesPerSeason: 20,
  speedPointsPerSeason: 5,
  devUpsPerSeason: 2,
  ageResetsPerSeason: 2,
  legendsAllTime: 4,
  maxLegendsInInventory: 4,
  maxLegendsPlusCustomPlayers: 7,
} as const;

export const ATTRIBUTES = [
  "Speed",
  "Acceleration",
  "Agility",
  "Strength",
  "Awareness",
  "Carrying",
  "BC Vision",
  "Break Tackle",
  "Trucking",
  "Stiff Arm",
  "Change of Direction",
  "Spin Move",
  "Juke Move",
  "Catching",
  "Catch in Traffic",
  "Spectacular Catch",
  "Short Route Running",
  "Medium Route Running",
  "Deep Route Running",
  "Release",
  "Jumping",
  "Throwing Power",
  "Short Accuracy",
  "Medium Accuracy",
  "Deep Accuracy",
  "Throw on the Run",
  "Throw Under Pressure",
  "Break Sack",
  "Play Action",
  "Pass Blocking",
  "Pass Block Power",
  "Pass Block Finesse",
  "Run Blocking",
  "Run Block Power",
  "Run Block Finesse",
  "Lead Block",
  "Impact Blocking",
  "Play Recognition",
  "Tackling",
  "Hit Power",
  "Block Shedding",
  "Finesse Moves",
  "Power Moves",
  "Pursuit",
  "Man Coverage",
  "Zone Coverage",
  "Press",
  "Kick/Punt Return",
  "Kicking Power",
  "Kicking Accuracy",
  "Stamina",
  "Toughness",
  "Injury",
  "Long Snap",
] as const;

export const DEV_UP_TYPES = ["Star", "Superstar"] as const;

export const CUSTOM_PLAYER_TIERS = ["gold", "silver", "bronze"] as const;

export const NFL_TEAMS = [
  "Bears",
  "Bengals",
  "Bills",
  "Broncos",
  "Browns",
  "Buccaneers",
  "Cardinals",
  "Chargers",
  "Chiefs",
  "Colts",
  "Cowboys",
  "Dolphins",
  "Eagles",
  "Falcons",
  "Giants",
  "Jaguars",
  "Jets",
  "Lions",
  "Packers",
  "Panthers",
  "Patriots",
  "Raiders",
  "Rams",
  "Ravens",
  "Saints",
  "Seahawks",
  "Steelers",
  "Texans",
  "Titans",
  "Vikings",
  "Commanders",
  "49ers",
] as const;

export type NFLTeam = typeof NFL_TEAMS[number];
