// Question pools for the Press Conference feature.
// 150 trash-talk prompts (used by the Trash Talk Opponent option — 2 are
// drawn per session) and 150 general prompts (used by the General Interview
// option — 3 are drawn per session). Keep questions short enough to render
// cleanly as TextInput labels (≤ ~100 chars).

export const TRASH_TALK_QUESTIONS: readonly string[] = [
  "What's the one weakness in your opponent's offense you plan to exploit?",
  "What does your opponent do better than anyone else — and why won't it matter this week?",
  "If your opponent's coach had one fatal flaw, what would it be?",
  "What's the most overrated player on your opponent's roster?",
  "Be honest — do you respect your opponent's playcalling, or is it predictable?",
  "What's a bad habit you've noticed in your opponent's game film?",
  "How much of your opponent's success is talent vs. cheese?",
  "If your opponent loses this week, how should they explain it to their fanbase?",
  "What's the one play you'd run again and again on this defense?",
  "Why is your opponent's record fool's gold?",
  "What would you say to fans who think your opponent has the better team?",
  "Has your opponent ever beaten you when it actually mattered?",
  "Describe your opponent's scheme in one word — and not a nice one.",
  "What's the biggest mismatch in your favor this week?",
  "If you could ban one play from your opponent's playbook, what would it be?",
  "How seriously should anyone take your opponent's playoff hopes?",
  "What's the one stat that proves your opponent isn't as good as their record?",
  "If your opponent's QB had to start for your team, would they even crack the depth chart?",
  "How would you describe your opponent's running game to a stranger?",
  "What's the most embarrassing loss in your opponent's recent history?",
  "Is there anyone on your opponent's roster you'd actually trade for? Why not?",
  "What's the most arrogant thing your opponent has done in this league?",
  "How do you plan to silence the crowd this week?",
  "What's something your opponent's coaching staff keeps getting wrong?",
  "If you had to face your opponent in the playoffs, would they make it past the first round?",
  "What's the difference between confidence and the noise coming from your opponent's camp?",
  "What's a snap count you'll exploit against this opponent?",
  "How much does it bother you that your opponent gets more hype than you?",
  "What's the over/under on how many turnovers your opponent gives up this week?",
  "If your opponent's offense is a movie, what's it called and how does it end?",
  "What's the worst decision your opponent has made all season?",
  "Why do you think your opponent always seems to fold in the fourth quarter?",
  "What's one piece of advice you'd give your opponent that they'd ignore?",
  "Be honest — could your opponent's starting line even block your backups?",
  "What play call would make you laugh if you saw your opponent run it Sunday?",
  "How does it feel knowing your opponent has to scheme everything around stopping you?",
  "What's your opponent's biggest excuse going to be when they lose this week?",
  "If your opponent had your roster, how many wins do they get? Be honest.",
  "What's the most boring thing about playing your opponent?",
  "What's the most surprising thing about how badly your opponent prepares?",
  "Which of your opponent's players is most likely to disappear this week?",
  "If you could trash-talk one specific player on your opponent's team, who and why?",
  "What's the difference between hype and your opponent's actual film?",
  "How many of your opponent's wins were against teams that mattered?",
  "What's the loudest part of your opponent's game — the playcalling or the excuses?",
  "If your opponent's scheme had a soundtrack, what song would it be and why?",
  "What's the matchup your opponent is praying gets cancelled this week?",
  "How long until your opponent's front office cleans house?",
  "If you were game-planning against yourself, what would scare you more than your opponent does?",
  "How embarrassed should your opponent be if they don't put up at least 21 on you?",
  "What's the longest you'd give your opponent before they fold under pressure?",
  "What's the laziest thing your opponent does week after week?",
  "How obvious is your opponent's playcalling when they get into the red zone?",
  "What's the one part of your opponent's game that's straight up overrated by everyone?",
  "Be honest — do you even need to study film for this opponent?",
  "What's the most predictable third-down call your opponent runs?",
  "If your opponent's franchise had a slogan, what would it be?",
  "How would you describe your opponent's coaching staff in one savage sentence?",
  "What's the most embarrassing thing about your opponent's defense?",
  "If your opponent's offense was a fast food order, what would it be?",
  "What's the gap between what your opponent says and what they actually do?",
  "Be real — does anyone in this league actually fear your opponent?",
  "What's something your opponent does on third-and-long that's basically a free turnover?",
  "How tired are you of hearing about your opponent's preseason hype?",
  "If your opponent loses this week, how many people are actually shocked?",
  "What's the cheesiest play your opponent has run on you in the past?",
  "Has your opponent earned any of their wins, or have they just been gifted?",
  "What's your opponent's biggest blind spot — and how hard will you press it?",
  "If your opponent's GM had to evaluate their own team honestly, would they keep their job?",
  "How would you grade your opponent's offseason — and don't be polite?",
  "What's a stat your opponent quotes that doesn't actually mean anything?",
  "Be honest — does your opponent's QB scare anyone outside of his own locker room?",
  "What's the worst thing about going on the road to play your opponent?",
  "If you swapped coaches with your opponent for a week, who's winning more games?",
  "What's the one play in your playbook that you know your opponent has no answer for?",
  "How offended should we be that your opponent thinks they're a contender?",
  "Have you ever lost sleep over playing your opponent? Why or why not?",
  "What does your opponent's locker room sound like after they lose to you?",
  "If you could send your opponent one game film to teach them football, which one?",
  "What's something your opponent does that you'd never let your coordinator try?",
  "Are your opponent's playoff chances a hope or a fantasy?",
  "What's the most overhyped strength your opponent talks about every week?",
  "If you had your opponent's roster for one week, what's the first thing you'd change?",
  "How many quarters before your opponent benches their starting QB this week?",
  "What's the funniest thing your opponent's coach has said this season?",
  "Be brutally honest — would you trade your worst starter for your opponent's best?",
  "What's the dumbest formation your opponent keeps trotting out?",
  "What's the chance your opponent finishes above .500? And what's the chance pigs fly?",
  "How would you describe your opponent's culture — winning or just talking?",
  "What's the loudest piece of trash talk you've heard from your opponent this week?",
  "If your opponent had to start over from scratch, what would they do differently?",
  "What's the biggest gap between the league's perception of your opponent and reality?",
  "How much film do you really need to watch to beat this opponent?",
  "If your opponent's franchise was a sandwich, what would it be — and would you eat it?",
  "What's the one thing your opponent does that you genuinely respect — and why is it not enough?",
  "How would you describe your opponent's special teams — average, bad, or somehow worse?",
  "What's the biggest joke about your opponent's roster construction?",
  "If you and your opponent played a best-of-7, what's the score?",
  "What's something your opponent says before every game that ages terribly after the loss?",
  "How easy is it to read your opponent's hot routes pre-snap?",
  "Do you even need your A-game to beat this opponent? Be honest.",
  "What's the worst part of your opponent's playcalling — the calls, the timing, or the panic?",
  "How will you celebrate after putting your opponent's playoff hopes on life support?",
  "What's the most overhyped 'breakout' player on your opponent's roster?",
  "Is your opponent built for a Super Bowl run, or just built to lose in the wildcard round?",
  "How fast do you think your opponent's locker room turns on each other if you go up two scores?",
  "What's the dumbest thing your opponent has ever done on 4th-and-1 against you?",
  "If you spotted your opponent 7 points, would it even matter?",
  "How much of your opponent's offense disappears the second their RB has a bad game?",
  "What's the most fragile part of your opponent's defense — and how soon will you crack it?",
  "Be honest — would your opponent's starting unit even be a backup unit on your team?",
  "What's the most generous compliment you could give your opponent — and why is it still kind of an insult?",
  "How many times will your opponent punt before you put the game away?",
  "What's the one excuse your opponent will lean on after this game?",
  "Is your opponent's defense scheme actually clever, or just confusing to themselves?",
  "Why does your opponent always seem to start fast and then collapse?",
  "What's the one play that, if you call it, your opponent's whole season unravels?",
  "How embarrassed should your opponent's fans be if they lose by 14?",
  "What's the worst missed assignment you've ever seen from your opponent's defense?",
  "If your opponent had film of every play you'd run, would it even matter?",
  "What's the most amateur thing your opponent's offensive coordinator does on a weekly basis?",
  "How tired are you of your opponent acting like a contender every offseason?",
  "Is your opponent more dangerous on offense or more entertaining to laugh at on defense?",
  "What's the cheesiest blitz your opponent runs when they're desperate?",
  "How fast can you make your opponent abandon the run this week?",
  "If your opponent's offense had a personality, what would it be — boring or just bad?",
  "What's the play your opponent is gonna run on third down — and how easy is it to see coming?",
  "How long until your opponent's coach starts blaming his players in pressers?",
  "Be real — does your opponent's QB make any throw that actually scares you?",
  "What's the biggest myth about your opponent that the league keeps repeating?",
  "If your opponent could only run one play this game, what would it be — and how badly would it fail?",
  "How long do you think your opponent's coaching staff lasts after the season they're having?",
  "What's the most miserable thing about watching your opponent play football?",
  "How obvious is it that your opponent leans on one playmaker and prays?",
  "What's something your opponent thinks is a strength that's actually a glaring weakness?",
  "If your opponent makes the playoffs, who do you actually want to face — them or anyone else?",
  "What's the most worn-out talking point your opponent uses every week?",
  "How many points do you think you need to score before your opponent quits?",
  "Be honest — is your opponent's coach actually a head coach, or just lucky?",
  "What's the most amateur-hour mistake your opponent keeps repeating week after week?",
  "How do you plan to make your opponent's offense one-dimensional in the first quarter?",
  "What's the biggest gap between your opponent's confidence and their actual ability?",
  "If your opponent's roster was a draft class, what round would the whole team go in?",
  "How much would your opponent's record drop if they played a real schedule?",
  "What's the dumbest 4th-down decision you can imagine your opponent making this week?",
  "How quickly do you expect your opponent to start arguing on the sideline once they fall behind?",
  "Be honest — would you ever trust your opponent's QB in a 2-minute drill? Why not?",
  "What's the one thing your opponent has to do this week that they absolutely won't?",
  "How loud do you want it to be in the building when you bury this opponent?",
  "What's the most generous thing you could say about your opponent — and how much of a stretch is it?",
] as const;

export const GENERAL_QUESTIONS: readonly string[] = [
  "What's the identity you want your team to be known for this season?",
  "How would you describe your team's mindset heading into this stretch of games?",
  "What's the biggest lesson you've learned about your team so far?",
  "How are you handling the expectations placed on your franchise this year?",
  "Where do you think your team has improved the most since the start of the season?",
  "What's the area of your team that you're still trying to figure out?",
  "How do you keep the locker room focused after a tough loss?",
  "What's the message you give your team during the bye week?",
  "How would you grade your team's start to the season?",
  "What's the one thing you want every player on your roster to internalize?",
  "What's the toughest decision you've had to make as a coach this season?",
  "How do you balance developing young players with trying to win now?",
  "What does success look like for your franchise this year?",
  "What's one underrated player on your roster who deserves more attention?",
  "How do you handle players who push back on your scheme?",
  "What's the part of your job people would be most surprised by?",
  "How has your offensive philosophy evolved this year?",
  "What's something about your defense that you want fans to appreciate more?",
  "How important is special teams in shaping the final result of a game?",
  "Who's been the surprise of training camp turning into the regular season?",
  "What's a position group that you're especially proud of right now?",
  "What's a position group that still keeps you up at night?",
  "What's the conversation you have with your team after a blowout win?",
  "How do you keep a team hungry when things are going well?",
  "What's a stat you track that fans probably don't pay attention to?",
  "What's the hardest part of game planning for an unfamiliar opponent?",
  "What's a tradition or ritual your team relies on every game day?",
  "How do you build trust with a rookie quarterback?",
  "What's a play call you've wanted to dial up all season and haven't yet?",
  "How do you decide when to be aggressive on fourth down?",
  "What's something you tell your team before kickoff every single week?",
  "How do you handle the pressure of representing this fanbase?",
  "What's the moment in a game where you know you've got control?",
  "What's the difference between winning ugly and winning right?",
  "How do you handle a player who's losing confidence mid-season?",
  "What's something you wish more fans understood about coaching?",
  "How important is film study compared to feel during a game?",
  "What's an aspect of analytics you've come to rely on lately?",
  "How do you build chemistry between offense and defense?",
  "What's the most underrated stat in football?",
  "What's a quote you keep on your desk that drives you?",
  "Who's a coach you've stolen the most ideas from?",
  "How do you decide who calls plays — and would you ever give it up?",
  "What's a part of your job you genuinely love that nobody talks about?",
  "What's the most rewarding part of working with young players?",
  "How do you respond when your team plays down to their competition?",
  "What's the conversation in the locker room when you're going into halftime down two scores?",
  "What's your philosophy on benching a struggling starter?",
  "How important is the bye week for the rest of your season?",
  "What's a hard truth you've delivered to your team this year?",
  "How do you keep a long season from grinding your team down mentally?",
  "What's something your franchise has been building toward for multiple seasons?",
  "How important is the relationship between you and your offensive coordinator?",
  "What's a metric you use to evaluate your defensive backs?",
  "How do you decide who gets the goal line carries?",
  "What's something you've taught a rookie that they didn't expect to hear?",
  "How do you balance scheme creativity with executing the basics?",
  "What's the most important leadership trait on a winning team?",
  "How much does the schedule actually shape your season?",
  "Who's a player on your roster that has earned more snaps?",
  "How would you describe your team's culture in three words?",
  "What's something you'd change about how the league handles in-season trades?",
  "What's a personnel grouping you've been experimenting with?",
  "Who's a future captain on your roster nobody is talking about yet?",
  "What's the one drill in practice you refuse to skip?",
  "How do you keep your team focused during a winning streak?",
  "How do you keep your team from spiraling during a losing streak?",
  "What's the conversation you have with your QB after a four-interception game?",
  "What's the conversation you have with your QB after a four-touchdown game?",
  "What's a lesson from your worst loss this season?",
  "What's a moment this year that made you proud of your team?",
  "How do you handle media criticism after a tough Sunday?",
  "What's a stat about your team that nobody is talking about that should be?",
  "How important is your relationship with your defensive coordinator?",
  "What's a player on your roster who's quietly putting together an elite season?",
  "How do you measure progress when wins and losses aren't telling the full story?",
  "What's the most important habit your team has built since the start of the year?",
  "How would you describe your offensive identity in one play type?",
  "What's a coverage you've come to lean on the most this season?",
  "What's a blitz package you've added to the playbook this year?",
  "How do you decide when to challenge a call?",
  "What's the toughest part about preparing for a divisional matchup?",
  "How important are walk-throughs the day before a game?",
  "What's a part of your training camp that's stayed with you all season?",
  "Who's been your most reliable third-down receiver?",
  "What's a moment this season that changed how you see your own team?",
  "How do you handle the emotional swings of an NFL season?",
  "What's something about the league you'd love to see change?",
  "How would you describe your relationship with your front office?",
  "What's the most underrated job in a football organization?",
  "What's a player your scouts hit on that nobody else saw coming?",
  "How important is fan support to your team's home-field advantage?",
  "What's a road environment you actually enjoy playing in?",
  "What's a road environment that gives your team the most trouble?",
  "How important is winning the turnover battle in any given week?",
  "What's a stat you track for your offensive line that fans probably don't?",
  "How do you handle injuries to key starters mid-season?",
  "What's something about your defensive scheme you've kept quiet on purpose?",
  "Who's been the most coachable player on your team this year?",
  "How important is veteran leadership compared to young talent?",
  "What's a player on your roster who exemplifies what you want this team to be?",
  "How do you build trust with players who weren't drafted by you?",
  "What's an offseason move you're glad you made?",
  "What's a free agent you wish you had made a bigger push for?",
  "How would you grade your draft class so far?",
  "Who's the biggest steal of your most recent draft?",
  "What's a position you're already targeting for next year's draft?",
  "How important is positional versatility on a modern roster?",
  "What's a scheme trend in the league you think is overhyped?",
  "What's a scheme trend in the league you think is genuinely changing the game?",
  "How important is play-action to your offensive identity?",
  "What's a personnel package you're using more than fans realize?",
  "How do you decide when to lean on the run vs. the pass?",
  "What's the biggest improvement your offensive line has made this season?",
  "How important is the tight end position in your scheme?",
  "Who's a defensive lineman on your roster you wish got more attention?",
  "How important is pre-snap motion to your offense?",
  "What's something you'd love to install schematically but haven't yet?",
  "How do you build a championship-caliber culture from year one?",
  "What's the difference between a good franchise and a great one?",
  "How do you stay grounded during a hot stretch of games?",
  "What's the part of your daily routine you protect the most?",
  "How important is mental health awareness for your players?",
  "What's something you do to recharge during the season?",
  "How do you keep your assistant coaches engaged late in the year?",
  "What's the best advice another coach has ever given you?",
  "What's a lesson you've learned the hard way as a head coach?",
  "How important is community work for your players?",
  "What's a charity or cause that means a lot to your franchise?",
  "What's the most rewarding part of being in this position?",
  "How would you describe your leadership style in one sentence?",
  "What's something your team does well that doesn't show up on the scoreboard?",
  "How do you measure a successful week of practice?",
  "What's a coaching point your staff has been hammering this week?",
  "How important is winning the time of possession battle for your team?",
  "What's something your defense does on first down that sets the tone?",
  "Who's a player on your roster who could break out in the second half of the season?",
  "How do you balance trying to win this week with developing depth long-term?",
  "What's the most important thing you've added to your team's playbook this year?",
  "How would you describe your philosophy on situational football?",
  "What's a moment in the season that defined your team's character?",
  "How important is finishing the season strong, even if playoffs are out of reach?",
  "What's the one message you want your team to carry into the offseason?",
  "How do you build year-over-year continuity with so much league turnover?",
  "What's a goal you've set for your franchise that fans don't know about?",
  "How do you keep the locker room together when expectations aren't being met?",
  "What's a piece of your coaching philosophy that has never changed?",
  "What's something fans should look forward to from your team the rest of the way?",
  "What's a small thing this week — practice, meeting, film session — that's setting the tone for the rest of the season?",
  "If someone wrote the story of your franchise five years from now, what's the chapter title for this season?",
] as const;

// Sanity: we ship exactly 150 of each. Misnumbered pools would silently
// break the random-pick code below.
if (TRASH_TALK_QUESTIONS.length !== 150) {
  throw new Error(`TRASH_TALK_QUESTIONS expected 150 entries, got ${TRASH_TALK_QUESTIONS.length}`);
}
if (GENERAL_QUESTIONS.length !== 150) {
  throw new Error(`GENERAL_QUESTIONS expected 150 entries, got ${GENERAL_QUESTIONS.length}`);
}

export function pickRandomIndices(poolSize: number, n: number): number[] {
  const out: number[] = [];
  const used = new Set<number>();
  while (out.length < n && used.size < poolSize) {
    const idx = Math.floor(Math.random() * poolSize);
    if (!used.has(idx)) { used.add(idx); out.push(idx); }
  }
  return out;
}

export function pickQuestions(type: "trash_talk" | "general"): string[] {
  if (type === "trash_talk") {
    return pickRandomIndices(TRASH_TALK_QUESTIONS.length, 2).map((i) => TRASH_TALK_QUESTIONS[i]!);
  }
  return pickRandomIndices(GENERAL_QUESTIONS.length, 3).map((i) => GENERAL_QUESTIONS[i]!);
}
